### ISSUE TITLE
After attaching furigana, ebook is unreadable

### ISSUE THREAD

**Issue by temccarthy** [itsupera/furiganalyse#1]
I downloaded That Time I Got Reincarnated as a Slime from [syosetsu](https://ncode.syosetu.com/n6316bn/1/) using [WebNovelCrawler](https://github.com/tongyuantongyu/WebNovelCrawler) and tried uploading it to the webapp. At first I tried uploading the epub directly, but that results in **Error during conversion**, so then I tried uploading it as a zip and I was able to download a converted epub file. However, opening that file in Calibre results this error, indicating its not a properly formatted epub file: 

```
calibre, version 5.27.0
ERROR: Loading book failed: Failed to open the book at C:\Users\timot\Documents\Calibre Library\Unknown\furiganalysed slime (85)\furiganalysed slime - Unknown.epub. Click "Show details" for more info.

Failed to convert book: C:\Users\timot\Documents\Calibre Library\Unknown\furiganalysed slime (85)\furiganalysed slime - Unknown.epub with error:
WARNING: Epub doesn't contain a valid mimetype declaration
InputFormatPlugin: EPUB Input running
on C:\Users\timot\Documents\Calibre Library\Unknown\furiganalysed slime (85)\furiganalysed slime - Unknown.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre\ebooks\metadata\epub.py", line 99, in __init__
  File "calibre\ebooks\metadata\epub.py", line 153, in open
  File "calibre\utils\zipfile.py", line 1006, in read
  File "calibre\utils\zipfile.py", line 1034, in open
  File "calibre\utils\zipfile.py", line 995, in getinfo
KeyError: "There is no item named 'META-INF/container.xml' in the archive"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 433, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 169, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 238, in get_quick_metadata
  File "calibre\ebooks\metadata\epub.py", line 217, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 165, in get_zip_reader
  File "calibre\ebooks\metadata\epub.py", line 148, in __init__
  File "calibre\ebooks\metadata\epub.py", line 102, in __init__
calibre.ebooks.metadata.epub.EPubException: missing OCF container.xml file
Traceback (most recent call last):
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 241, in find_opf
FileNotFoundError: [Errno 2] No such file or directory: 'META-INF/container.xml'
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 824, in viewer_main
  File "calibre\srv\render_book.py", line 815, in render_for_viewer
  File "calibre\srv\render_book.py", line 792, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 281, in convert
ValueError: C:\Users\timot\Documents\Calibre Library\Unknown\furiganalysed slime (85)\furiganalysed slime - Unknown.epub is not a valid EPUB file (could not find opf)
```

I also tried downloading the conversion as 1 text file, but it downloaded an empty text file. Any thoughts?

**Comment by itsupera** [comment]
Sending the EPUB should work, but apparently something made the parsing code crash.
```
furiganalyse_1  | ERROR:root:Error while processing /tmp/furiganalysed_uploads/tmphddoa9qh/slime.epub: Traceback (most recent call last):                                                                          
furiganalyse_1  |   File "/workdir/furiganalyse/app.py", line 58, in get_post_upload_file                
furiganalyse_1  |     main(                                                                              
furiganalyse_1  |   File "/workdir/furiganalyse/__main__.py", line 33, in main                           
furiganalyse_1  |     process_epub_file(unzipped_input_fpath, furigana_mode, writing_mode, output_format)                                                                                                          
furiganalyse_1  |   File "/workdir/furiganalyse/epub_format.py", line 20, in process_epub_file           
furiganalyse_1  |     tree = process_html(html_filepath, mode)                                           
furiganalyse_1  |   File "/workdir/furiganalyse/parsing.py", line 15, in process_html                    
furiganalyse_1  |     process_tree(tree, mode)                                                           
furiganalyse_1  |   File "/workdir/furiganalyse/parsing.py", line 31, in process_tree                    
furiganalyse_1  |     process_head(p)                                                                    
furiganalyse_1  |   File "/workdir/furiganalyse/parsing.py", line 97, in process_head                    
furiganalyse_1  |     head, children, tail = create_parsed_furigana_html(text)                           
furiganalyse_1  |   File "/workdir/furiganalyse/parsing.py", line 132, in create_parsed_furigana_html    
furiganalyse_1  |     new_text = create_furigana_html(text)                                              
furiganalyse_1  |   File "/usr/local/lib/python3.8/site-packages/furigana/furigana.py", line 173, in create_furigana_html                                                                                          
furiganalyse_1  |     for pair in split_furigana(text):                                                  
furiganalyse_1  |   File "/usr/local/lib/python3.8/site-packages/furigana/furigana.py", line 136, in split_furigana                                                                                                
furiganalyse_1  |     texts = parse_node(node)                                                           
furiganalyse_1  |   File "/usr/local/lib/python3.8/site-packages/furigana/furigana.py", line 164, in parse_node
furiganalyse_1  |     return split_okurigana(origin, hiragana)
furiganalyse_1  |   File "/usr/local/lib/python3.8/site-packages/furigana/furigana.py", line 43, in split_okurigana
furiganalyse_1  |     logging.debug(f'Taking care non kanji parts. i={i}, j={j} ("{text[i]}" / "{hiragana[j]}")')
furiganalyse_1  | IndexError: string index out of range
```

Can you send me your EPUB file please? I will further investigate.

**Comment by temccarthy** [comment]
I uploaded it here: https://www.file.io/O8qW/download/SNRRczKIvvK3

**Comment by itsupera** [comment]
Thank you. I've fixed the issue, you can try again.
